import { createFileRoute } from '@tanstack/react-router'import { createFileRoute } from '@tanstack/react-router'


















































































































































































































































































































}  )    </div>      )}        </Card>          </CardContent>            </div>              ))}                </div>                  </div>                    </span>                      {user.goal}                    <span className="px-2 py-1 bg-primary/10 text-primary rounded">                  <div className="text-sm">                  </div>                    </div>                      {user.phoneNumber} • {user.role}                    <div className="text-sm text-muted-foreground">                    <div className="font-medium">{user.name}</div>                  <div>                >                  className="flex items-center justify-between p-3 border rounded"                  key={user._id}                <div              {allUsers.map((user) => (            <div className="space-y-2">          <CardContent>          </CardHeader>            <CardTitle>Current Users</CardTitle>          <CardHeader>        <Card>      {allUsers && allUsers.length > 0 && (      {/* Users List */}      </Card>        </CardContent>          </div>            </div>              </ul>                <li>✓ clearDatabase</li>                <li>✓ seedDatabase</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Seed</h4>            <div>            </div>              </ul>                <li>✓ getWeightLogsByUser</li>                <li>✓ addWeightLog</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Weight Logs</h4>            <div>            </div>              </ul>                <li>✓ unassignTrainingPlanFromUser</li>                <li>✓ assignTrainingPlanToUser</li>                <li>✓ deleteTrainingPlan</li>                <li>✓ updateTrainingPlan</li>                <li>✓ getTrainingPlanById</li>                <li>✓ getAllTrainingPlans</li>                <li>✓ getTrainingPlansByCreator</li>                <li>✓ createTrainingPlan</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Training Plans</h4>            <div>            </div>              </ul>                <li>✓ deleteDietPlan</li>                <li>✓ updateDietPlan</li>                <li>✓ getDietPlanById</li>                <li>✓ getDietPlansByUser</li>                <li>✓ createDietPlan</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Diet Plans</h4>            <div>            </div>              </ul>                <li>✓ getDietStats</li>                <li>✓ updateDietLog</li>                <li>✓ deleteDietLog</li>                <li>✓ getTodayCalories</li>                <li>✓ getTodayDietLogs</li>                <li>✓ getDietLogsByUser</li>                <li>✓ addDietLog</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Diet Logs</h4>            <div>            </div>              </ul>                <li>✓ deleteExercise</li>                <li>✓ updateExercise</li>                <li>✓ getExercisesByWorkoutLog</li>                <li>✓ addExercises</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Workouts (Exercises)</h4>            <div>            </div>              </ul>                <li>✓ getWorkoutStats</li>                <li>✓ deleteWorkoutLog</li>                <li>✓ cancelWorkoutLog</li>                <li>✓ completeWorkoutLog</li>                <li>✓ getOngoingWorkout</li>                <li>✓ getWorkoutLogsByUser</li>                <li>✓ createWorkoutLog</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Workout Logs</h4>            <div>            </div>              </ul>                <li>✓ searchUsers</li>                <li>✓ updateUserMeta</li>                <li>✓ getUserWithMeta</li>                <li>✓ deleteUser</li>                <li>✓ updateUser</li>                <li>✓ getUsersByTrainer</li>                <li>✓ getAllUsers</li>                <li>✓ getUserById</li>                <li>✓ createUser</li>                <li>✓ signInQuery</li>              <ul className="space-y-1 text-muted-foreground">              <h4 className="font-semibold mb-2">Users</h4>            <div>          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">        <CardContent>        </CardHeader>          <CardTitle>Available Backend Functions</CardTitle>        <CardHeader>      <Card>      {/* Available Backend Functions */}      </Card>        </CardContent>          </div>            </div>              </div>                Goal: Endurance              <div className="text-xs text-muted-foreground">              <div>PIN: 444444</div>              <div>Phone: 4444444444</div>              <div className="font-bold text-pink-600">Client 3 (Emma)</div>            <div className="space-y-2">            </div>              </div>                Goal: Muscle Gain              <div className="text-xs text-muted-foreground">              <div>PIN: 333333</div>              <div>Phone: 3333333333</div>              <div className="font-bold text-orange-600">Client 2 (Mike)</div>            <div className="space-y-2">            </div>              </div>                Goal: Weight Loss              <div className="text-xs text-muted-foreground">              <div>PIN: 222222</div>              <div>Phone: 2222222222</div>              <div className="font-bold text-purple-600">Client 1 (Sarah)</div>            <div className="space-y-2">            </div>              <div>PIN: 111111</div>              <div>Phone: 1111111111</div>              <div className="font-bold text-green-600">Trainer</div>            <div className="space-y-2">            </div>              <div>PIN: 000000</div>              <div>Phone: 1000000000</div>              <div className="font-bold text-blue-600">Admin</div>            <div className="space-y-2">          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-sm">        <CardContent>        </CardHeader>          <CardTitle>Sample Login Credentials</CardTitle>        <CardHeader>      <Card>      {/* Sample Login Credentials */}      </div>        </Card>          </CardContent>            </p>              Your diet plans            <p className="text-sm text-muted-foreground mt-2">            <div className="text-4xl font-bold">{dietPlans?.length || 0}</div>          <CardContent>          </CardHeader>            <CardTitle>Diet Plans</CardTitle>          <CardHeader>        <Card>        </Card>          </CardContent>            </p>              Total training plans            <p className="text-sm text-muted-foreground mt-2">            </div>              {trainingPlans?.length || 0}            <div className="text-4xl font-bold">          <CardContent>          </CardHeader>            <CardTitle>Training Plans</CardTitle>          <CardHeader>        <Card>        </Card>          </CardContent>            </p>              Total users in database            <p className="text-sm text-muted-foreground mt-2">            <div className="text-4xl font-bold">{allUsers?.length || 0}</div>          <CardContent>          </CardHeader>            <CardTitle>Users</CardTitle>          <CardHeader>        <Card>      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">      {/* Current Data */}      </Card>        </CardContent>          </div>            </p>              (⚠️ Dangerous!)              <strong>Clear Database:</strong> Remove ALL data from ALL tables            <p>            </p>              logs, etc.              <strong>Seed Database:</strong> Populate with sample users, plans,            <p>          <div className="text-sm text-muted-foreground space-y-1">          </div>            </Button>              🗑️ Clear Database            <Button onClick={handleClear} variant="destructive" className="flex-1">            </Button>              🌱 Seed Database            <Button onClick={handleSeed} className="flex-1">          <div className="flex gap-4">        <CardContent className="space-y-4">        </CardHeader>          <CardTitle>Database Controls</CardTitle>        <CardHeader>      <Card>      {/* Seed Controls */}      </header>        </p>          Test all backend functions and seed the database        <p className="text-muted-foreground mt-2">        <h1 className="text-3xl font-bold">Backend Integration Test</h1>      <header>    <div className="min-h-screen bg-background p-6 space-y-6">  return (  }    }      console.error('Clear error:', error)      toast.error('Failed to clear database')    } catch (error) {      console.log('Clear result:', result)      toast.success('Database cleared successfully!')      const result = await clearDatabase()    try {    }      return    ) {      )        'Are you sure you want to clear ALL data? This cannot be undone!',      !confirm(    if (  const handleClear = async () => {  }    }      console.error('Seed error:', error)      toast.error('Failed to seed database')    } catch (error) {      console.log('Seed result:', result)      toast.success('Database seeded successfully!')      const result = await seedDatabase()    try {  const handleSeed = async () => {  )    user ? { userId: user._id } : 'skip',    api.dietPlans.getDietPlansByUser,  const dietPlans = useQuery(  const trainingPlans = useQuery(api.trainingPlans.getAllTrainingPlans)  const allUsers = useQuery(api.users.getAllUsers)  // Test queries  const clearDatabase = useMutation(api.seed.clearDatabase)  const seedDatabase = useMutation(api.seed.seedDatabase)  const { user } = useAuth()function RouteComponent() {})  component: RouteComponent,export const Route = createFileRoute('/app/management/test-integration')({import { useAuth } from '@/components/auth/useAuth'import { toast } from 'sonner'import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'import { Button } from '@/components/ui/button'import { api } from '../../../../convex/_generated/api'import { useMutation, useQuery } from 'convex/react'
export const Route = createFileRoute('/app/management/test-integration')({
  component: RouteComponent,
})

function RouteComponent() {
  return <div>Hello "/app/management/test-integration"!</div>
}
