/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as AppUserRouteImport } from './routes/app/_user'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppManagementRouteRouteImport } from './routes/app/management/route'
import { Route as AppSignInRouteImport } from './routes/app/sign-in'
import { Route as AppUserIndexRouteImport } from './routes/app/_user/index'
import { Route as AppUserAccountRouteImport } from './routes/app/_user/account'
import { Route as AppUserDashboardRouteImport } from './routes/app/_user/dashboard'
import { Route as AppUserDietHistoryRouteImport } from './routes/app/_user/diet-history'
import { Route as AppUserDietLogsRouteImport } from './routes/app/_user/diet-logs'
import { Route as AppUserDietPlanRouteImport } from './routes/app/_user/diet-plan'
import { Route as AppUserGalleryRouteImport } from './routes/app/_user/gallery'
import { Route as AppUserLogsRouteImport } from './routes/app/_user/logs'
import { Route as AppUserSessionsRouteImport } from './routes/app/_user/sessions'
import { Route as AppUserSuccessStoryRouteImport } from './routes/app/_user/success-story'
import { Route as AppUserWeightRouteImport } from './routes/app/_user/weight'
import { Route as AppUserWorkoutSessionRouteImport } from './routes/app/_user/workout-session'
import { Route as AppUserWorkoutsRouteImport } from './routes/app/_user/workouts'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminProfileRouteImport } from './routes/app/admin/profile'
import { Route as AppAdminProfileAboutRouteImport } from './routes/app/admin/profile-about'
import { Route as AppAdminProfileExercisesRouteImport } from './routes/app/admin/profile-exercises'
import { Route as AppAdminProfileImagesRouteImport } from './routes/app/admin/profile-images'
import { Route as AppAdminProfileStoriesRouteImport } from './routes/app/admin/profile-stories'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppManagementProfileRouteImport } from './routes/app/management/profile'
import { Route as AppUserRoutinesRoutineIdRouteImport } from './routes/app/_user/routines/$routineId'
import { Route as AppUserWorkoutWeekPlansPlanIdRouteImport } from './routes/app/_user/workout-week-plans/$planId'
import { Route as AppAdminListIndexRouteImport } from './routes/app/admin/list/index'
import { Route as AppAdminListClientIdRouteImport } from './routes/app/admin/list/$clientId'
import { Route as AppAdminListSelfManagedRouteImport } from './routes/app/admin/list/self-managed'
import { Route as AppAdminListTrainerManagedRouteImport } from './routes/app/admin/list/trainer-managed'
import { Route as AppAdminListTrainersRouteImport } from './routes/app/admin/list/trainers'
import { Route as AppAdminProfileStoryNewRouteImport } from './routes/app/admin/profile-story/new'
import { Route as AppManagementClientsIndexRouteImport } from './routes/app/management/clients/index'
import { Route as AppManagementDietPlansIndexRouteImport } from './routes/app/management/diet-plans/index'
import { Route as AppManagementDietPlansPlanIdRouteImport } from './routes/app/management/diet-plans/$planId'
import { Route as AppManagementDietPlansNewRouteImport } from './routes/app/management/diet-plans/new'
import { Route as AppManagementRoutinesIndexRouteImport } from './routes/app/management/routines/index'
import { Route as AppManagementRoutinesRoutineIdRouteImport } from './routes/app/management/routines/$routineId'
import { Route as AppManagementRoutinesNewRouteImport } from './routes/app/management/routines/new'
import { Route as AppAdminListPatternClientIdRouteImport } from './routes/app/admin/list/pattern/$clientId'
import { Route as AppAdminListViewWorkClientIdRouteImport } from './routes/app/admin/list/view-work/$clientId'
import { Route as AppAdminProfileStoryStoryIdEditRouteImport } from './routes/app/admin/profile-story/$storyId.edit'
import { Route as AppManagementClientsClientIdIndexRouteImport } from './routes/app/management/clients/$clientId/index'
import { Route as AppManagementClientsClientIdCheckRouteImport } from './routes/app/management/clients/$clientId/check'
import { Route as AppManagementClientsClientIdPatternRouteImport } from './routes/app/management/clients/$clientId/pattern'
import { Route as AppManagementClientsClientIdViewWorkRouteImport } from './routes/app/management/clients/$clientId/view-work'
import { Route as AppManagementClientsClientIdWorkoutSessionRouteImport } from './routes/app/management/clients/$clientId/workout-session'
import { Route as AppManagementRoutinesWeekPlansPlanIdRouteImport } from './routes/app/management/routines/week-plans/$planId'
import { Route as AppAdminListLogsDietClientIdRouteImport } from './routes/app/admin/list/logs/diet/$clientId'
import { Route as AppAdminListLogsWeightClientIdRouteImport } from './routes/app/admin/list/logs/weight/$clientId'
import { Route as AppManagementClientsClientIdLogsDietRouteImport } from './routes/app/management/clients/$clientId/logs/diet'
import { Route as AppManagementClientsClientIdLogsWeightRouteImport } from './routes/app/management/clients/$clientId/logs/weight'
import { Route as AppManagementClientsClientIdLogsWorkoutRouteImport } from './routes/app/management/clients/$clientId/logs/workout'
import { Route as AppManagementClientsClientIdRoutinesRoutineIdRouteImport } from './routes/app/management/clients/$clientId/routines/$routineId'
import { Route as AppManagementClientsClientIdRoutinesNewRouteImport } from './routes/app/management/clients/$clientId/routines/new'
import { Route as AppManagementClientsClientIdRoutinesWeekPlansPlanIdRouteImport } from './routes/app/management/clients/$clientId/routines/week-plans/$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/app/_user',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementRouteRoute = AppManagementRouteRouteImport.update({
  id: '/app/management',
  path: '/app/management',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignInRoute = AppSignInRouteImport.update({
  id: '/app/sign-in',
  path: '/app/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserAccountRoute = AppUserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserDashboardRoute = AppUserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserDietHistoryRoute = AppUserDietHistoryRouteImport.update({
  id: '/diet-history',
  path: '/diet-history',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserDietLogsRoute = AppUserDietLogsRouteImport.update({
  id: '/diet-logs',
  path: '/diet-logs',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserDietPlanRoute = AppUserDietPlanRouteImport.update({
  id: '/diet-plan',
  path: '/diet-plan',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserGalleryRoute = AppUserGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserLogsRoute = AppUserLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserSessionsRoute = AppUserSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserSuccessStoryRoute = AppUserSuccessStoryRouteImport.update({
  id: '/success-story',
  path: '/success-story',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserWeightRoute = AppUserWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserWorkoutSessionRoute = AppUserWorkoutSessionRouteImport.update({
  id: '/workout-session',
  path: '/workout-session',
  getParentRoute: () => AppUserRoute,
} as any)
const AppUserWorkoutsRoute = AppUserWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppUserRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileRoute = AppAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileAboutRoute = AppAdminProfileAboutRouteImport.update({
  id: '/profile-about',
  path: '/profile-about',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileExercisesRoute =
  AppAdminProfileExercisesRouteImport.update({
    id: '/profile-exercises',
    path: '/profile-exercises',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminProfileImagesRoute = AppAdminProfileImagesRouteImport.update({
  id: '/profile-images',
  path: '/profile-images',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileStoriesRoute = AppAdminProfileStoriesRouteImport.update({
  id: '/profile-stories',
  path: '/profile-stories',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagementRouteRoute,
} as any)
const AppManagementProfileRoute = AppManagementProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppManagementRouteRoute,
} as any)
const AppUserRoutinesRoutineIdRoute =
  AppUserRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => AppUserRoute,
  } as any)
const AppUserWorkoutWeekPlansPlanIdRoute =
  AppUserWorkoutWeekPlansPlanIdRouteImport.update({
    id: '/workout-week-plans/$planId',
    path: '/workout-week-plans/$planId',
    getParentRoute: () => AppUserRoute,
  } as any)
const AppAdminListIndexRoute = AppAdminListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminListClientIdRoute = AppAdminListClientIdRouteImport.update({
  id: '/list/$clientId',
  path: '/list/$clientId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminListSelfManagedRoute = AppAdminListSelfManagedRouteImport.update({
  id: '/list/self-managed',
  path: '/list/self-managed',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminListTrainerManagedRoute =
  AppAdminListTrainerManagedRouteImport.update({
    id: '/list/trainer-managed',
    path: '/list/trainer-managed',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminListTrainersRoute = AppAdminListTrainersRouteImport.update({
  id: '/list/trainers',
  path: '/list/trainers',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileStoryNewRoute = AppAdminProfileStoryNewRouteImport.update({
  id: '/profile-story/new',
  path: '/profile-story/new',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppManagementClientsIndexRoute =
  AppManagementClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementDietPlansIndexRoute =
  AppManagementDietPlansIndexRouteImport.update({
    id: '/diet-plans/',
    path: '/diet-plans/',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementDietPlansPlanIdRoute =
  AppManagementDietPlansPlanIdRouteImport.update({
    id: '/diet-plans/$planId',
    path: '/diet-plans/$planId',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementDietPlansNewRoute =
  AppManagementDietPlansNewRouteImport.update({
    id: '/diet-plans/new',
    path: '/diet-plans/new',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementRoutinesIndexRoute =
  AppManagementRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementRoutinesRoutineIdRoute =
  AppManagementRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementRoutinesNewRoute =
  AppManagementRoutinesNewRouteImport.update({
    id: '/routines/new',
    path: '/routines/new',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppAdminListPatternClientIdRoute =
  AppAdminListPatternClientIdRouteImport.update({
    id: '/list/pattern/$clientId',
    path: '/list/pattern/$clientId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminListViewWorkClientIdRoute =
  AppAdminListViewWorkClientIdRouteImport.update({
    id: '/list/view-work/$clientId',
    path: '/list/view-work/$clientId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminProfileStoryStoryIdEditRoute =
  AppAdminProfileStoryStoryIdEditRouteImport.update({
    id: '/profile-story/$storyId/edit',
    path: '/profile-story/$storyId/edit',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppManagementClientsClientIdIndexRoute =
  AppManagementClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdCheckRoute =
  AppManagementClientsClientIdCheckRouteImport.update({
    id: '/clients/$clientId/check',
    path: '/clients/$clientId/check',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdPatternRoute =
  AppManagementClientsClientIdPatternRouteImport.update({
    id: '/clients/$clientId/pattern',
    path: '/clients/$clientId/pattern',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdViewWorkRoute =
  AppManagementClientsClientIdViewWorkRouteImport.update({
    id: '/clients/$clientId/view-work',
    path: '/clients/$clientId/view-work',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdWorkoutSessionRoute =
  AppManagementClientsClientIdWorkoutSessionRouteImport.update({
    id: '/clients/$clientId/workout-session',
    path: '/clients/$clientId/workout-session',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementRoutinesWeekPlansPlanIdRoute =
  AppManagementRoutinesWeekPlansPlanIdRouteImport.update({
    id: '/routines/week-plans/$planId',
    path: '/routines/week-plans/$planId',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppAdminListLogsDietClientIdRoute =
  AppAdminListLogsDietClientIdRouteImport.update({
    id: '/list/logs/diet/$clientId',
    path: '/list/logs/diet/$clientId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminListLogsWeightClientIdRoute =
  AppAdminListLogsWeightClientIdRouteImport.update({
    id: '/list/logs/weight/$clientId',
    path: '/list/logs/weight/$clientId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppManagementClientsClientIdLogsDietRoute =
  AppManagementClientsClientIdLogsDietRouteImport.update({
    id: '/clients/$clientId/logs/diet',
    path: '/clients/$clientId/logs/diet',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdLogsWeightRoute =
  AppManagementClientsClientIdLogsWeightRouteImport.update({
    id: '/clients/$clientId/logs/weight',
    path: '/clients/$clientId/logs/weight',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdLogsWorkoutRoute =
  AppManagementClientsClientIdLogsWorkoutRouteImport.update({
    id: '/clients/$clientId/logs/workout',
    path: '/clients/$clientId/logs/workout',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdRoutinesRoutineIdRoute =
  AppManagementClientsClientIdRoutinesRoutineIdRouteImport.update({
    id: '/clients/$clientId/routines/$routineId',
    path: '/clients/$clientId/routines/$routineId',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdRoutinesNewRoute =
  AppManagementClientsClientIdRoutinesNewRouteImport.update({
    id: '/clients/$clientId/routines/new',
    path: '/clients/$clientId/routines/new',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)
const AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute =
  AppManagementClientsClientIdRoutinesWeekPlansPlanIdRouteImport.update({
    id: '/clients/$clientId/routines/week-plans/$planId',
    path: '/clients/$clientId/routines/week-plans/$planId',
    getParentRoute: () => AppManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app': typeof AppUserRouteWithChildren
  '/app/sign-in': typeof AppSignInRoute
  '/api/': typeof ApiIndexRoute
  '/app/account': typeof AppUserAccountRoute
  '/app/dashboard': typeof AppUserDashboardRoute
  '/app/diet-history': typeof AppUserDietHistoryRoute
  '/app/diet-logs': typeof AppUserDietLogsRoute
  '/app/diet-plan': typeof AppUserDietPlanRoute
  '/app/gallery': typeof AppUserGalleryRoute
  '/app/logs': typeof AppUserLogsRoute
  '/app/sessions': typeof AppUserSessionsRoute
  '/app/success-story': typeof AppUserSuccessStoryRoute
  '/app/weight': typeof AppUserWeightRoute
  '/app/workout-session': typeof AppUserWorkoutSessionRoute
  '/app/workouts': typeof AppUserWorkoutsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/profile-about': typeof AppAdminProfileAboutRoute
  '/app/admin/profile-exercises': typeof AppAdminProfileExercisesRoute
  '/app/admin/profile-images': typeof AppAdminProfileImagesRoute
  '/app/admin/profile-stories': typeof AppAdminProfileStoriesRoute
  '/app/management/profile': typeof AppManagementProfileRoute
  '/app/': typeof AppUserIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/routines/$routineId': typeof AppUserRoutinesRoutineIdRoute
  '/app/workout-week-plans/$planId': typeof AppUserWorkoutWeekPlansPlanIdRoute
  '/app/admin/list/$clientId': typeof AppAdminListClientIdRoute
  '/app/admin/list/self-managed': typeof AppAdminListSelfManagedRoute
  '/app/admin/list/trainer-managed': typeof AppAdminListTrainerManagedRoute
  '/app/admin/list/trainers': typeof AppAdminListTrainersRoute
  '/app/admin/profile-story/new': typeof AppAdminProfileStoryNewRoute
  '/app/management/diet-plans/$planId': typeof AppManagementDietPlansPlanIdRoute
  '/app/management/diet-plans/new': typeof AppManagementDietPlansNewRoute
  '/app/management/routines/$routineId': typeof AppManagementRoutinesRoutineIdRoute
  '/app/management/routines/new': typeof AppManagementRoutinesNewRoute
  '/app/admin/list/': typeof AppAdminListIndexRoute
  '/app/management/clients/': typeof AppManagementClientsIndexRoute
  '/app/management/diet-plans/': typeof AppManagementDietPlansIndexRoute
  '/app/management/routines/': typeof AppManagementRoutinesIndexRoute
  '/app/admin/list/pattern/$clientId': typeof AppAdminListPatternClientIdRoute
  '/app/admin/list/view-work/$clientId': typeof AppAdminListViewWorkClientIdRoute
  '/app/admin/profile-story/$storyId/edit': typeof AppAdminProfileStoryStoryIdEditRoute
  '/app/management/clients/$clientId/check': typeof AppManagementClientsClientIdCheckRoute
  '/app/management/clients/$clientId/pattern': typeof AppManagementClientsClientIdPatternRoute
  '/app/management/clients/$clientId/view-work': typeof AppManagementClientsClientIdViewWorkRoute
  '/app/management/clients/$clientId/workout-session': typeof AppManagementClientsClientIdWorkoutSessionRoute
  '/app/management/routines/week-plans/$planId': typeof AppManagementRoutinesWeekPlansPlanIdRoute
  '/app/management/clients/$clientId/': typeof AppManagementClientsClientIdIndexRoute
  '/app/admin/list/logs/diet/$clientId': typeof AppAdminListLogsDietClientIdRoute
  '/app/admin/list/logs/weight/$clientId': typeof AppAdminListLogsWeightClientIdRoute
  '/app/management/clients/$clientId/logs/diet': typeof AppManagementClientsClientIdLogsDietRoute
  '/app/management/clients/$clientId/logs/weight': typeof AppManagementClientsClientIdLogsWeightRoute
  '/app/management/clients/$clientId/logs/workout': typeof AppManagementClientsClientIdLogsWorkoutRoute
  '/app/management/clients/$clientId/routines/$routineId': typeof AppManagementClientsClientIdRoutinesRoutineIdRoute
  '/app/management/clients/$clientId/routines/new': typeof AppManagementClientsClientIdRoutinesNewRoute
  '/app/management/clients/$clientId/routines/week-plans/$planId': typeof AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/sign-in': typeof AppSignInRoute
  '/api': typeof ApiIndexRoute
  '/app/account': typeof AppUserAccountRoute
  '/app/dashboard': typeof AppUserDashboardRoute
  '/app/diet-history': typeof AppUserDietHistoryRoute
  '/app/diet-logs': typeof AppUserDietLogsRoute
  '/app/diet-plan': typeof AppUserDietPlanRoute
  '/app/gallery': typeof AppUserGalleryRoute
  '/app/logs': typeof AppUserLogsRoute
  '/app/sessions': typeof AppUserSessionsRoute
  '/app/success-story': typeof AppUserSuccessStoryRoute
  '/app/weight': typeof AppUserWeightRoute
  '/app/workout-session': typeof AppUserWorkoutSessionRoute
  '/app/workouts': typeof AppUserWorkoutsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/profile-about': typeof AppAdminProfileAboutRoute
  '/app/admin/profile-exercises': typeof AppAdminProfileExercisesRoute
  '/app/admin/profile-images': typeof AppAdminProfileImagesRoute
  '/app/admin/profile-stories': typeof AppAdminProfileStoriesRoute
  '/app/management/profile': typeof AppManagementProfileRoute
  '/app': typeof AppUserIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/management': typeof AppManagementIndexRoute
  '/app/routines/$routineId': typeof AppUserRoutinesRoutineIdRoute
  '/app/workout-week-plans/$planId': typeof AppUserWorkoutWeekPlansPlanIdRoute
  '/app/admin/list/$clientId': typeof AppAdminListClientIdRoute
  '/app/admin/list/self-managed': typeof AppAdminListSelfManagedRoute
  '/app/admin/list/trainer-managed': typeof AppAdminListTrainerManagedRoute
  '/app/admin/list/trainers': typeof AppAdminListTrainersRoute
  '/app/admin/profile-story/new': typeof AppAdminProfileStoryNewRoute
  '/app/management/diet-plans/$planId': typeof AppManagementDietPlansPlanIdRoute
  '/app/management/diet-plans/new': typeof AppManagementDietPlansNewRoute
  '/app/management/routines/$routineId': typeof AppManagementRoutinesRoutineIdRoute
  '/app/management/routines/new': typeof AppManagementRoutinesNewRoute
  '/app/admin/list': typeof AppAdminListIndexRoute
  '/app/management/clients': typeof AppManagementClientsIndexRoute
  '/app/management/diet-plans': typeof AppManagementDietPlansIndexRoute
  '/app/management/routines': typeof AppManagementRoutinesIndexRoute
  '/app/admin/list/pattern/$clientId': typeof AppAdminListPatternClientIdRoute
  '/app/admin/list/view-work/$clientId': typeof AppAdminListViewWorkClientIdRoute
  '/app/admin/profile-story/$storyId/edit': typeof AppAdminProfileStoryStoryIdEditRoute
  '/app/management/clients/$clientId/check': typeof AppManagementClientsClientIdCheckRoute
  '/app/management/clients/$clientId/pattern': typeof AppManagementClientsClientIdPatternRoute
  '/app/management/clients/$clientId/view-work': typeof AppManagementClientsClientIdViewWorkRoute
  '/app/management/clients/$clientId/workout-session': typeof AppManagementClientsClientIdWorkoutSessionRoute
  '/app/management/routines/week-plans/$planId': typeof AppManagementRoutinesWeekPlansPlanIdRoute
  '/app/management/clients/$clientId': typeof AppManagementClientsClientIdIndexRoute
  '/app/admin/list/logs/diet/$clientId': typeof AppAdminListLogsDietClientIdRoute
  '/app/admin/list/logs/weight/$clientId': typeof AppAdminListLogsWeightClientIdRoute
  '/app/management/clients/$clientId/logs/diet': typeof AppManagementClientsClientIdLogsDietRoute
  '/app/management/clients/$clientId/logs/weight': typeof AppManagementClientsClientIdLogsWeightRoute
  '/app/management/clients/$clientId/logs/workout': typeof AppManagementClientsClientIdLogsWorkoutRoute
  '/app/management/clients/$clientId/routines/$routineId': typeof AppManagementClientsClientIdRoutinesRoutineIdRoute
  '/app/management/clients/$clientId/routines/new': typeof AppManagementClientsClientIdRoutinesNewRoute
  '/app/management/clients/$clientId/routines/week-plans/$planId': typeof AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app/_user': typeof AppUserRouteWithChildren
  '/app/sign-in': typeof AppSignInRoute
  '/api/': typeof ApiIndexRoute
  '/app/_user/account': typeof AppUserAccountRoute
  '/app/_user/dashboard': typeof AppUserDashboardRoute
  '/app/_user/diet-history': typeof AppUserDietHistoryRoute
  '/app/_user/diet-logs': typeof AppUserDietLogsRoute
  '/app/_user/diet-plan': typeof AppUserDietPlanRoute
  '/app/_user/gallery': typeof AppUserGalleryRoute
  '/app/_user/logs': typeof AppUserLogsRoute
  '/app/_user/sessions': typeof AppUserSessionsRoute
  '/app/_user/success-story': typeof AppUserSuccessStoryRoute
  '/app/_user/weight': typeof AppUserWeightRoute
  '/app/_user/workout-session': typeof AppUserWorkoutSessionRoute
  '/app/_user/workouts': typeof AppUserWorkoutsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/profile-about': typeof AppAdminProfileAboutRoute
  '/app/admin/profile-exercises': typeof AppAdminProfileExercisesRoute
  '/app/admin/profile-images': typeof AppAdminProfileImagesRoute
  '/app/admin/profile-stories': typeof AppAdminProfileStoriesRoute
  '/app/management/profile': typeof AppManagementProfileRoute
  '/app/_user/': typeof AppUserIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/_user/routines/$routineId': typeof AppUserRoutinesRoutineIdRoute
  '/app/_user/workout-week-plans/$planId': typeof AppUserWorkoutWeekPlansPlanIdRoute
  '/app/admin/list/$clientId': typeof AppAdminListClientIdRoute
  '/app/admin/list/self-managed': typeof AppAdminListSelfManagedRoute
  '/app/admin/list/trainer-managed': typeof AppAdminListTrainerManagedRoute
  '/app/admin/list/trainers': typeof AppAdminListTrainersRoute
  '/app/admin/profile-story/new': typeof AppAdminProfileStoryNewRoute
  '/app/management/diet-plans/$planId': typeof AppManagementDietPlansPlanIdRoute
  '/app/management/diet-plans/new': typeof AppManagementDietPlansNewRoute
  '/app/management/routines/$routineId': typeof AppManagementRoutinesRoutineIdRoute
  '/app/management/routines/new': typeof AppManagementRoutinesNewRoute
  '/app/admin/list/': typeof AppAdminListIndexRoute
  '/app/management/clients/': typeof AppManagementClientsIndexRoute
  '/app/management/diet-plans/': typeof AppManagementDietPlansIndexRoute
  '/app/management/routines/': typeof AppManagementRoutinesIndexRoute
  '/app/admin/list/pattern/$clientId': typeof AppAdminListPatternClientIdRoute
  '/app/admin/list/view-work/$clientId': typeof AppAdminListViewWorkClientIdRoute
  '/app/admin/profile-story/$storyId/edit': typeof AppAdminProfileStoryStoryIdEditRoute
  '/app/management/clients/$clientId/check': typeof AppManagementClientsClientIdCheckRoute
  '/app/management/clients/$clientId/pattern': typeof AppManagementClientsClientIdPatternRoute
  '/app/management/clients/$clientId/view-work': typeof AppManagementClientsClientIdViewWorkRoute
  '/app/management/clients/$clientId/workout-session': typeof AppManagementClientsClientIdWorkoutSessionRoute
  '/app/management/routines/week-plans/$planId': typeof AppManagementRoutinesWeekPlansPlanIdRoute
  '/app/management/clients/$clientId/': typeof AppManagementClientsClientIdIndexRoute
  '/app/admin/list/logs/diet/$clientId': typeof AppAdminListLogsDietClientIdRoute
  '/app/admin/list/logs/weight/$clientId': typeof AppAdminListLogsWeightClientIdRoute
  '/app/management/clients/$clientId/logs/diet': typeof AppManagementClientsClientIdLogsDietRoute
  '/app/management/clients/$clientId/logs/weight': typeof AppManagementClientsClientIdLogsWeightRoute
  '/app/management/clients/$clientId/logs/workout': typeof AppManagementClientsClientIdLogsWorkoutRoute
  '/app/management/clients/$clientId/routines/$routineId': typeof AppManagementClientsClientIdRoutinesRoutineIdRoute
  '/app/management/clients/$clientId/routines/new': typeof AppManagementClientsClientIdRoutinesNewRoute
  '/app/management/clients/$clientId/routines/week-plans/$planId': typeof AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/admin'
    | '/app/management'
    | '/app'
    | '/app/sign-in'
    | '/api/'
    | '/app/account'
    | '/app/dashboard'
    | '/app/diet-history'
    | '/app/diet-logs'
    | '/app/diet-plan'
    | '/app/gallery'
    | '/app/logs'
    | '/app/sessions'
    | '/app/success-story'
    | '/app/weight'
    | '/app/workout-session'
    | '/app/workouts'
    | '/app/admin/profile'
    | '/app/admin/profile-about'
    | '/app/admin/profile-exercises'
    | '/app/admin/profile-images'
    | '/app/admin/profile-stories'
    | '/app/management/profile'
    | '/app/'
    | '/app/admin/'
    | '/app/management/'
    | '/app/routines/$routineId'
    | '/app/workout-week-plans/$planId'
    | '/app/admin/list/$clientId'
    | '/app/admin/list/self-managed'
    | '/app/admin/list/trainer-managed'
    | '/app/admin/list/trainers'
    | '/app/admin/profile-story/new'
    | '/app/management/diet-plans/$planId'
    | '/app/management/diet-plans/new'
    | '/app/management/routines/$routineId'
    | '/app/management/routines/new'
    | '/app/admin/list/'
    | '/app/management/clients/'
    | '/app/management/diet-plans/'
    | '/app/management/routines/'
    | '/app/admin/list/pattern/$clientId'
    | '/app/admin/list/view-work/$clientId'
    | '/app/admin/profile-story/$storyId/edit'
    | '/app/management/clients/$clientId/check'
    | '/app/management/clients/$clientId/pattern'
    | '/app/management/clients/$clientId/view-work'
    | '/app/management/clients/$clientId/workout-session'
    | '/app/management/routines/week-plans/$planId'
    | '/app/management/clients/$clientId/'
    | '/app/admin/list/logs/diet/$clientId'
    | '/app/admin/list/logs/weight/$clientId'
    | '/app/management/clients/$clientId/logs/diet'
    | '/app/management/clients/$clientId/logs/weight'
    | '/app/management/clients/$clientId/logs/workout'
    | '/app/management/clients/$clientId/routines/$routineId'
    | '/app/management/clients/$clientId/routines/new'
    | '/app/management/clients/$clientId/routines/week-plans/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/sign-in'
    | '/api'
    | '/app/account'
    | '/app/dashboard'
    | '/app/diet-history'
    | '/app/diet-logs'
    | '/app/diet-plan'
    | '/app/gallery'
    | '/app/logs'
    | '/app/sessions'
    | '/app/success-story'
    | '/app/weight'
    | '/app/workout-session'
    | '/app/workouts'
    | '/app/admin/profile'
    | '/app/admin/profile-about'
    | '/app/admin/profile-exercises'
    | '/app/admin/profile-images'
    | '/app/admin/profile-stories'
    | '/app/management/profile'
    | '/app'
    | '/app/admin'
    | '/app/management'
    | '/app/routines/$routineId'
    | '/app/workout-week-plans/$planId'
    | '/app/admin/list/$clientId'
    | '/app/admin/list/self-managed'
    | '/app/admin/list/trainer-managed'
    | '/app/admin/list/trainers'
    | '/app/admin/profile-story/new'
    | '/app/management/diet-plans/$planId'
    | '/app/management/diet-plans/new'
    | '/app/management/routines/$routineId'
    | '/app/management/routines/new'
    | '/app/admin/list'
    | '/app/management/clients'
    | '/app/management/diet-plans'
    | '/app/management/routines'
    | '/app/admin/list/pattern/$clientId'
    | '/app/admin/list/view-work/$clientId'
    | '/app/admin/profile-story/$storyId/edit'
    | '/app/management/clients/$clientId/check'
    | '/app/management/clients/$clientId/pattern'
    | '/app/management/clients/$clientId/view-work'
    | '/app/management/clients/$clientId/workout-session'
    | '/app/management/routines/week-plans/$planId'
    | '/app/management/clients/$clientId'
    | '/app/admin/list/logs/diet/$clientId'
    | '/app/admin/list/logs/weight/$clientId'
    | '/app/management/clients/$clientId/logs/diet'
    | '/app/management/clients/$clientId/logs/weight'
    | '/app/management/clients/$clientId/logs/workout'
    | '/app/management/clients/$clientId/routines/$routineId'
    | '/app/management/clients/$clientId/routines/new'
    | '/app/management/clients/$clientId/routines/week-plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/app/admin'
    | '/app/management'
    | '/app/_user'
    | '/app/sign-in'
    | '/api/'
    | '/app/_user/account'
    | '/app/_user/dashboard'
    | '/app/_user/diet-history'
    | '/app/_user/diet-logs'
    | '/app/_user/diet-plan'
    | '/app/_user/gallery'
    | '/app/_user/logs'
    | '/app/_user/sessions'
    | '/app/_user/success-story'
    | '/app/_user/weight'
    | '/app/_user/workout-session'
    | '/app/_user/workouts'
    | '/app/admin/profile'
    | '/app/admin/profile-about'
    | '/app/admin/profile-exercises'
    | '/app/admin/profile-images'
    | '/app/admin/profile-stories'
    | '/app/management/profile'
    | '/app/_user/'
    | '/app/admin/'
    | '/app/management/'
    | '/app/_user/routines/$routineId'
    | '/app/_user/workout-week-plans/$planId'
    | '/app/admin/list/$clientId'
    | '/app/admin/list/self-managed'
    | '/app/admin/list/trainer-managed'
    | '/app/admin/list/trainers'
    | '/app/admin/profile-story/new'
    | '/app/management/diet-plans/$planId'
    | '/app/management/diet-plans/new'
    | '/app/management/routines/$routineId'
    | '/app/management/routines/new'
    | '/app/admin/list/'
    | '/app/management/clients/'
    | '/app/management/diet-plans/'
    | '/app/management/routines/'
    | '/app/admin/list/pattern/$clientId'
    | '/app/admin/list/view-work/$clientId'
    | '/app/admin/profile-story/$storyId/edit'
    | '/app/management/clients/$clientId/check'
    | '/app/management/clients/$clientId/pattern'
    | '/app/management/clients/$clientId/view-work'
    | '/app/management/clients/$clientId/workout-session'
    | '/app/management/routines/week-plans/$planId'
    | '/app/management/clients/$clientId/'
    | '/app/admin/list/logs/diet/$clientId'
    | '/app/admin/list/logs/weight/$clientId'
    | '/app/management/clients/$clientId/logs/diet'
    | '/app/management/clients/$clientId/logs/weight'
    | '/app/management/clients/$clientId/logs/workout'
    | '/app/management/clients/$clientId/routines/$routineId'
    | '/app/management/clients/$clientId/routines/new'
    | '/app/management/clients/$clientId/routines/week-plans/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppManagementRouteRoute: typeof AppManagementRouteRouteWithChildren
  AppUserRoute: typeof AppUserRouteWithChildren
  AppSignInRoute: typeof AppSignInRoute
  ApiIndexRoute: typeof ApiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_user': {
      id: '/app/_user'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management': {
      id: '/app/management'
      path: '/app/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sign-in': {
      id: '/app/sign-in'
      path: '/app/sign-in'
      fullPath: '/app/sign-in'
      preLoaderRoute: typeof AppSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_user/': {
      id: '/app/_user/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/account': {
      id: '/app/_user/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppUserAccountRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/dashboard': {
      id: '/app/_user/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppUserDashboardRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/diet-history': {
      id: '/app/_user/diet-history'
      path: '/diet-history'
      fullPath: '/app/diet-history'
      preLoaderRoute: typeof AppUserDietHistoryRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/diet-logs': {
      id: '/app/_user/diet-logs'
      path: '/diet-logs'
      fullPath: '/app/diet-logs'
      preLoaderRoute: typeof AppUserDietLogsRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/diet-plan': {
      id: '/app/_user/diet-plan'
      path: '/diet-plan'
      fullPath: '/app/diet-plan'
      preLoaderRoute: typeof AppUserDietPlanRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/gallery': {
      id: '/app/_user/gallery'
      path: '/gallery'
      fullPath: '/app/gallery'
      preLoaderRoute: typeof AppUserGalleryRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/logs': {
      id: '/app/_user/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppUserLogsRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/sessions': {
      id: '/app/_user/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppUserSessionsRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/success-story': {
      id: '/app/_user/success-story'
      path: '/success-story'
      fullPath: '/app/success-story'
      preLoaderRoute: typeof AppUserSuccessStoryRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/weight': {
      id: '/app/_user/weight'
      path: '/weight'
      fullPath: '/app/weight'
      preLoaderRoute: typeof AppUserWeightRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/workout-session': {
      id: '/app/_user/workout-session'
      path: '/workout-session'
      fullPath: '/app/workout-session'
      preLoaderRoute: typeof AppUserWorkoutSessionRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/workouts': {
      id: '/app/_user/workouts'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AppUserWorkoutsRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile': {
      id: '/app/admin/profile'
      path: '/profile'
      fullPath: '/app/admin/profile'
      preLoaderRoute: typeof AppAdminProfileRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-about': {
      id: '/app/admin/profile-about'
      path: '/profile-about'
      fullPath: '/app/admin/profile-about'
      preLoaderRoute: typeof AppAdminProfileAboutRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-exercises': {
      id: '/app/admin/profile-exercises'
      path: '/profile-exercises'
      fullPath: '/app/admin/profile-exercises'
      preLoaderRoute: typeof AppAdminProfileExercisesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-images': {
      id: '/app/admin/profile-images'
      path: '/profile-images'
      fullPath: '/app/admin/profile-images'
      preLoaderRoute: typeof AppAdminProfileImagesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-stories': {
      id: '/app/admin/profile-stories'
      path: '/profile-stories'
      fullPath: '/app/admin/profile-stories'
      preLoaderRoute: typeof AppAdminProfileStoriesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/profile': {
      id: '/app/management/profile'
      path: '/profile'
      fullPath: '/app/management/profile'
      preLoaderRoute: typeof AppManagementProfileRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/_user/routines/$routineId': {
      id: '/app/_user/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/app/routines/$routineId'
      preLoaderRoute: typeof AppUserRoutinesRoutineIdRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/_user/workout-week-plans/$planId': {
      id: '/app/_user/workout-week-plans/$planId'
      path: '/workout-week-plans/$planId'
      fullPath: '/app/workout-week-plans/$planId'
      preLoaderRoute: typeof AppUserWorkoutWeekPlansPlanIdRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/admin/list/': {
      id: '/app/admin/list/'
      path: '/list'
      fullPath: '/app/admin/list/'
      preLoaderRoute: typeof AppAdminListIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/$clientId': {
      id: '/app/admin/list/$clientId'
      path: '/list/$clientId'
      fullPath: '/app/admin/list/$clientId'
      preLoaderRoute: typeof AppAdminListClientIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/self-managed': {
      id: '/app/admin/list/self-managed'
      path: '/list/self-managed'
      fullPath: '/app/admin/list/self-managed'
      preLoaderRoute: typeof AppAdminListSelfManagedRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/trainer-managed': {
      id: '/app/admin/list/trainer-managed'
      path: '/list/trainer-managed'
      fullPath: '/app/admin/list/trainer-managed'
      preLoaderRoute: typeof AppAdminListTrainerManagedRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/trainers': {
      id: '/app/admin/list/trainers'
      path: '/list/trainers'
      fullPath: '/app/admin/list/trainers'
      preLoaderRoute: typeof AppAdminListTrainersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-story/new': {
      id: '/app/admin/profile-story/new'
      path: '/profile-story/new'
      fullPath: '/app/admin/profile-story/new'
      preLoaderRoute: typeof AppAdminProfileStoryNewRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/management/clients/': {
      id: '/app/management/clients/'
      path: '/clients'
      fullPath: '/app/management/clients/'
      preLoaderRoute: typeof AppManagementClientsIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/diet-plans/': {
      id: '/app/management/diet-plans/'
      path: '/diet-plans'
      fullPath: '/app/management/diet-plans/'
      preLoaderRoute: typeof AppManagementDietPlansIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/diet-plans/$planId': {
      id: '/app/management/diet-plans/$planId'
      path: '/diet-plans/$planId'
      fullPath: '/app/management/diet-plans/$planId'
      preLoaderRoute: typeof AppManagementDietPlansPlanIdRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/diet-plans/new': {
      id: '/app/management/diet-plans/new'
      path: '/diet-plans/new'
      fullPath: '/app/management/diet-plans/new'
      preLoaderRoute: typeof AppManagementDietPlansNewRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/routines/': {
      id: '/app/management/routines/'
      path: '/routines'
      fullPath: '/app/management/routines/'
      preLoaderRoute: typeof AppManagementRoutinesIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/routines/$routineId': {
      id: '/app/management/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/app/management/routines/$routineId'
      preLoaderRoute: typeof AppManagementRoutinesRoutineIdRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/routines/new': {
      id: '/app/management/routines/new'
      path: '/routines/new'
      fullPath: '/app/management/routines/new'
      preLoaderRoute: typeof AppManagementRoutinesNewRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/admin/list/pattern/$clientId': {
      id: '/app/admin/list/pattern/$clientId'
      path: '/list/pattern/$clientId'
      fullPath: '/app/admin/list/pattern/$clientId'
      preLoaderRoute: typeof AppAdminListPatternClientIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/view-work/$clientId': {
      id: '/app/admin/list/view-work/$clientId'
      path: '/list/view-work/$clientId'
      fullPath: '/app/admin/list/view-work/$clientId'
      preLoaderRoute: typeof AppAdminListViewWorkClientIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile-story/$storyId/edit': {
      id: '/app/admin/profile-story/$storyId/edit'
      path: '/profile-story/$storyId/edit'
      fullPath: '/app/admin/profile-story/$storyId/edit'
      preLoaderRoute: typeof AppAdminProfileStoryStoryIdEditRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/management/clients/$clientId/': {
      id: '/app/management/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/app/management/clients/$clientId/'
      preLoaderRoute: typeof AppManagementClientsClientIdIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/check': {
      id: '/app/management/clients/$clientId/check'
      path: '/clients/$clientId/check'
      fullPath: '/app/management/clients/$clientId/check'
      preLoaderRoute: typeof AppManagementClientsClientIdCheckRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/pattern': {
      id: '/app/management/clients/$clientId/pattern'
      path: '/clients/$clientId/pattern'
      fullPath: '/app/management/clients/$clientId/pattern'
      preLoaderRoute: typeof AppManagementClientsClientIdPatternRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/view-work': {
      id: '/app/management/clients/$clientId/view-work'
      path: '/clients/$clientId/view-work'
      fullPath: '/app/management/clients/$clientId/view-work'
      preLoaderRoute: typeof AppManagementClientsClientIdViewWorkRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/workout-session': {
      id: '/app/management/clients/$clientId/workout-session'
      path: '/clients/$clientId/workout-session'
      fullPath: '/app/management/clients/$clientId/workout-session'
      preLoaderRoute: typeof AppManagementClientsClientIdWorkoutSessionRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/routines/week-plans/$planId': {
      id: '/app/management/routines/week-plans/$planId'
      path: '/routines/week-plans/$planId'
      fullPath: '/app/management/routines/week-plans/$planId'
      preLoaderRoute: typeof AppManagementRoutinesWeekPlansPlanIdRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/admin/list/logs/diet/$clientId': {
      id: '/app/admin/list/logs/diet/$clientId'
      path: '/list/logs/diet/$clientId'
      fullPath: '/app/admin/list/logs/diet/$clientId'
      preLoaderRoute: typeof AppAdminListLogsDietClientIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/list/logs/weight/$clientId': {
      id: '/app/admin/list/logs/weight/$clientId'
      path: '/list/logs/weight/$clientId'
      fullPath: '/app/admin/list/logs/weight/$clientId'
      preLoaderRoute: typeof AppAdminListLogsWeightClientIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/management/clients/$clientId/logs/diet': {
      id: '/app/management/clients/$clientId/logs/diet'
      path: '/clients/$clientId/logs/diet'
      fullPath: '/app/management/clients/$clientId/logs/diet'
      preLoaderRoute: typeof AppManagementClientsClientIdLogsDietRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/logs/weight': {
      id: '/app/management/clients/$clientId/logs/weight'
      path: '/clients/$clientId/logs/weight'
      fullPath: '/app/management/clients/$clientId/logs/weight'
      preLoaderRoute: typeof AppManagementClientsClientIdLogsWeightRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/logs/workout': {
      id: '/app/management/clients/$clientId/logs/workout'
      path: '/clients/$clientId/logs/workout'
      fullPath: '/app/management/clients/$clientId/logs/workout'
      preLoaderRoute: typeof AppManagementClientsClientIdLogsWorkoutRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/routines/$routineId': {
      id: '/app/management/clients/$clientId/routines/$routineId'
      path: '/clients/$clientId/routines/$routineId'
      fullPath: '/app/management/clients/$clientId/routines/$routineId'
      preLoaderRoute: typeof AppManagementClientsClientIdRoutinesRoutineIdRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/routines/new': {
      id: '/app/management/clients/$clientId/routines/new'
      path: '/clients/$clientId/routines/new'
      fullPath: '/app/management/clients/$clientId/routines/new'
      preLoaderRoute: typeof AppManagementClientsClientIdRoutinesNewRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/management/clients/$clientId/routines/week-plans/$planId': {
      id: '/app/management/clients/$clientId/routines/week-plans/$planId'
      path: '/clients/$clientId/routines/week-plans/$planId'
      fullPath: '/app/management/clients/$clientId/routines/week-plans/$planId'
      preLoaderRoute: typeof AppManagementClientsClientIdRoutinesWeekPlansPlanIdRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminProfileRoute: typeof AppAdminProfileRoute
  AppAdminProfileAboutRoute: typeof AppAdminProfileAboutRoute
  AppAdminProfileExercisesRoute: typeof AppAdminProfileExercisesRoute
  AppAdminProfileImagesRoute: typeof AppAdminProfileImagesRoute
  AppAdminProfileStoriesRoute: typeof AppAdminProfileStoriesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminListClientIdRoute: typeof AppAdminListClientIdRoute
  AppAdminListSelfManagedRoute: typeof AppAdminListSelfManagedRoute
  AppAdminListTrainerManagedRoute: typeof AppAdminListTrainerManagedRoute
  AppAdminListTrainersRoute: typeof AppAdminListTrainersRoute
  AppAdminProfileStoryNewRoute: typeof AppAdminProfileStoryNewRoute
  AppAdminListIndexRoute: typeof AppAdminListIndexRoute
  AppAdminListPatternClientIdRoute: typeof AppAdminListPatternClientIdRoute
  AppAdminListViewWorkClientIdRoute: typeof AppAdminListViewWorkClientIdRoute
  AppAdminProfileStoryStoryIdEditRoute: typeof AppAdminProfileStoryStoryIdEditRoute
  AppAdminListLogsDietClientIdRoute: typeof AppAdminListLogsDietClientIdRoute
  AppAdminListLogsWeightClientIdRoute: typeof AppAdminListLogsWeightClientIdRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminProfileRoute: AppAdminProfileRoute,
  AppAdminProfileAboutRoute: AppAdminProfileAboutRoute,
  AppAdminProfileExercisesRoute: AppAdminProfileExercisesRoute,
  AppAdminProfileImagesRoute: AppAdminProfileImagesRoute,
  AppAdminProfileStoriesRoute: AppAdminProfileStoriesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminListClientIdRoute: AppAdminListClientIdRoute,
  AppAdminListSelfManagedRoute: AppAdminListSelfManagedRoute,
  AppAdminListTrainerManagedRoute: AppAdminListTrainerManagedRoute,
  AppAdminListTrainersRoute: AppAdminListTrainersRoute,
  AppAdminProfileStoryNewRoute: AppAdminProfileStoryNewRoute,
  AppAdminListIndexRoute: AppAdminListIndexRoute,
  AppAdminListPatternClientIdRoute: AppAdminListPatternClientIdRoute,
  AppAdminListViewWorkClientIdRoute: AppAdminListViewWorkClientIdRoute,
  AppAdminProfileStoryStoryIdEditRoute: AppAdminProfileStoryStoryIdEditRoute,
  AppAdminListLogsDietClientIdRoute: AppAdminListLogsDietClientIdRoute,
  AppAdminListLogsWeightClientIdRoute: AppAdminListLogsWeightClientIdRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppManagementRouteRouteChildren {
  AppManagementProfileRoute: typeof AppManagementProfileRoute
  AppManagementIndexRoute: typeof AppManagementIndexRoute
  AppManagementDietPlansPlanIdRoute: typeof AppManagementDietPlansPlanIdRoute
  AppManagementDietPlansNewRoute: typeof AppManagementDietPlansNewRoute
  AppManagementRoutinesRoutineIdRoute: typeof AppManagementRoutinesRoutineIdRoute
  AppManagementRoutinesNewRoute: typeof AppManagementRoutinesNewRoute
  AppManagementClientsIndexRoute: typeof AppManagementClientsIndexRoute
  AppManagementDietPlansIndexRoute: typeof AppManagementDietPlansIndexRoute
  AppManagementRoutinesIndexRoute: typeof AppManagementRoutinesIndexRoute
  AppManagementClientsClientIdCheckRoute: typeof AppManagementClientsClientIdCheckRoute
  AppManagementClientsClientIdPatternRoute: typeof AppManagementClientsClientIdPatternRoute
  AppManagementClientsClientIdViewWorkRoute: typeof AppManagementClientsClientIdViewWorkRoute
  AppManagementClientsClientIdWorkoutSessionRoute: typeof AppManagementClientsClientIdWorkoutSessionRoute
  AppManagementRoutinesWeekPlansPlanIdRoute: typeof AppManagementRoutinesWeekPlansPlanIdRoute
  AppManagementClientsClientIdIndexRoute: typeof AppManagementClientsClientIdIndexRoute
  AppManagementClientsClientIdLogsDietRoute: typeof AppManagementClientsClientIdLogsDietRoute
  AppManagementClientsClientIdLogsWeightRoute: typeof AppManagementClientsClientIdLogsWeightRoute
  AppManagementClientsClientIdLogsWorkoutRoute: typeof AppManagementClientsClientIdLogsWorkoutRoute
  AppManagementClientsClientIdRoutinesRoutineIdRoute: typeof AppManagementClientsClientIdRoutinesRoutineIdRoute
  AppManagementClientsClientIdRoutinesNewRoute: typeof AppManagementClientsClientIdRoutinesNewRoute
  AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute: typeof AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute
}

const AppManagementRouteRouteChildren: AppManagementRouteRouteChildren = {
  AppManagementProfileRoute: AppManagementProfileRoute,
  AppManagementIndexRoute: AppManagementIndexRoute,
  AppManagementDietPlansPlanIdRoute: AppManagementDietPlansPlanIdRoute,
  AppManagementDietPlansNewRoute: AppManagementDietPlansNewRoute,
  AppManagementRoutinesRoutineIdRoute: AppManagementRoutinesRoutineIdRoute,
  AppManagementRoutinesNewRoute: AppManagementRoutinesNewRoute,
  AppManagementClientsIndexRoute: AppManagementClientsIndexRoute,
  AppManagementDietPlansIndexRoute: AppManagementDietPlansIndexRoute,
  AppManagementRoutinesIndexRoute: AppManagementRoutinesIndexRoute,
  AppManagementClientsClientIdCheckRoute:
    AppManagementClientsClientIdCheckRoute,
  AppManagementClientsClientIdPatternRoute:
    AppManagementClientsClientIdPatternRoute,
  AppManagementClientsClientIdViewWorkRoute:
    AppManagementClientsClientIdViewWorkRoute,
  AppManagementClientsClientIdWorkoutSessionRoute:
    AppManagementClientsClientIdWorkoutSessionRoute,
  AppManagementRoutinesWeekPlansPlanIdRoute:
    AppManagementRoutinesWeekPlansPlanIdRoute,
  AppManagementClientsClientIdIndexRoute:
    AppManagementClientsClientIdIndexRoute,
  AppManagementClientsClientIdLogsDietRoute:
    AppManagementClientsClientIdLogsDietRoute,
  AppManagementClientsClientIdLogsWeightRoute:
    AppManagementClientsClientIdLogsWeightRoute,
  AppManagementClientsClientIdLogsWorkoutRoute:
    AppManagementClientsClientIdLogsWorkoutRoute,
  AppManagementClientsClientIdRoutinesRoutineIdRoute:
    AppManagementClientsClientIdRoutinesRoutineIdRoute,
  AppManagementClientsClientIdRoutinesNewRoute:
    AppManagementClientsClientIdRoutinesNewRoute,
  AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute:
    AppManagementClientsClientIdRoutinesWeekPlansPlanIdRoute,
}

const AppManagementRouteRouteWithChildren =
  AppManagementRouteRoute._addFileChildren(AppManagementRouteRouteChildren)

interface AppUserRouteChildren {
  AppUserAccountRoute: typeof AppUserAccountRoute
  AppUserDashboardRoute: typeof AppUserDashboardRoute
  AppUserDietHistoryRoute: typeof AppUserDietHistoryRoute
  AppUserDietLogsRoute: typeof AppUserDietLogsRoute
  AppUserDietPlanRoute: typeof AppUserDietPlanRoute
  AppUserGalleryRoute: typeof AppUserGalleryRoute
  AppUserLogsRoute: typeof AppUserLogsRoute
  AppUserSessionsRoute: typeof AppUserSessionsRoute
  AppUserSuccessStoryRoute: typeof AppUserSuccessStoryRoute
  AppUserWeightRoute: typeof AppUserWeightRoute
  AppUserWorkoutSessionRoute: typeof AppUserWorkoutSessionRoute
  AppUserWorkoutsRoute: typeof AppUserWorkoutsRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
  AppUserRoutinesRoutineIdRoute: typeof AppUserRoutinesRoutineIdRoute
  AppUserWorkoutWeekPlansPlanIdRoute: typeof AppUserWorkoutWeekPlansPlanIdRoute
}

const AppUserRouteChildren: AppUserRouteChildren = {
  AppUserAccountRoute: AppUserAccountRoute,
  AppUserDashboardRoute: AppUserDashboardRoute,
  AppUserDietHistoryRoute: AppUserDietHistoryRoute,
  AppUserDietLogsRoute: AppUserDietLogsRoute,
  AppUserDietPlanRoute: AppUserDietPlanRoute,
  AppUserGalleryRoute: AppUserGalleryRoute,
  AppUserLogsRoute: AppUserLogsRoute,
  AppUserSessionsRoute: AppUserSessionsRoute,
  AppUserSuccessStoryRoute: AppUserSuccessStoryRoute,
  AppUserWeightRoute: AppUserWeightRoute,
  AppUserWorkoutSessionRoute: AppUserWorkoutSessionRoute,
  AppUserWorkoutsRoute: AppUserWorkoutsRoute,
  AppUserIndexRoute: AppUserIndexRoute,
  AppUserRoutinesRoutineIdRoute: AppUserRoutinesRoutineIdRoute,
  AppUserWorkoutWeekPlansPlanIdRoute: AppUserWorkoutWeekPlansPlanIdRoute,
}

const AppUserRouteWithChildren =
  AppUserRoute._addFileChildren(AppUserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppManagementRouteRoute: AppManagementRouteRouteWithChildren,
  AppUserRoute: AppUserRouteWithChildren,
  AppSignInRoute: AppSignInRoute,
  ApiIndexRoute: ApiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
