/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as AppWorkoutsRouteImport } from './routes/app/workouts'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppManagementRouteRouteImport } from './routes/app/management/route'
import { Route as AppAccountRouteRouteImport } from './routes/app/account/route'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppAccountAboutRouteImport } from './routes/app/account/about'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManagementRouteRoute = AppManagementRouteRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagementRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountAboutRoute = AppAccountAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/workouts': typeof AppWorkoutsRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/account/about': typeof AppAccountAboutRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/workouts': typeof AppWorkoutsRoute
  '/api': typeof ApiIndexRoute
  '/app': typeof AppIndexRoute
  '/app/account/about': typeof AppAccountAboutRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/management': typeof AppManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/workouts': typeof AppWorkoutsRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/account/about': typeof AppAccountAboutRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/account'
    | '/app/management'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/workouts'
    | '/api/'
    | '/app/'
    | '/app/account/about'
    | '/app/account/'
    | '/app/management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/workouts'
    | '/api'
    | '/app'
    | '/app/account/about'
    | '/app/account'
    | '/app/management'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/account'
    | '/app/management'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/workouts'
    | '/api/'
    | '/app/'
    | '/app/account/about'
    | '/app/account/'
    | '/app/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiIndexRoute: typeof ApiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workouts': {
      id: '/app/workouts'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/management': {
      id: '/app/management'
      path: '/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/app/account/about': {
      id: '/app/account/about'
      path: '/about'
      fullPath: '/app/account/about'
      preLoaderRoute: typeof AppAccountAboutRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
  }
}

interface AppAccountRouteRouteChildren {
  AppAccountAboutRoute: typeof AppAccountAboutRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountAboutRoute: AppAccountAboutRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppManagementRouteRouteChildren {
  AppManagementIndexRoute: typeof AppManagementIndexRoute
}

const AppManagementRouteRouteChildren: AppManagementRouteRouteChildren = {
  AppManagementIndexRoute: AppManagementIndexRoute,
}

const AppManagementRouteRouteWithChildren =
  AppManagementRouteRoute._addFileChildren(AppManagementRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppManagementRouteRoute: typeof AppManagementRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLogsRoute: typeof AppLogsRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppManagementRouteRoute: AppManagementRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLogsRoute: AppLogsRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiIndexRoute: ApiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
