/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagementRouteRouteImport } from './routes/app/management/route'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppUserIndexRouteImport } from './routes/app/_user/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementRouteRoute = AppManagementRouteRouteImport.update({
  id: '/app/management',
  path: '/app/management',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagementRouteRoute,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/app/_user/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app': typeof AppUserIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppUserIndexRoute
  '/app/management': typeof AppManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/management': typeof AppManagementRouteRouteWithChildren
  '/app/_user/': typeof AppUserIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/management' | '/app' | '/app/management/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/management'
  id: '__root__' | '/' | '/app/management' | '/app/_user/' | '/app/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppManagementRouteRoute: typeof AppManagementRouteRouteWithChildren
  AppUserIndexRoute: typeof AppUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management': {
      id: '/app/management'
      path: '/app/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof AppManagementRouteRoute
    }
    '/app/_user/': {
      id: '/app/_user/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppManagementRouteRouteChildren {
  AppManagementIndexRoute: typeof AppManagementIndexRoute
}

const AppManagementRouteRouteChildren: AppManagementRouteRouteChildren = {
  AppManagementIndexRoute: AppManagementIndexRoute,
}

const AppManagementRouteRouteWithChildren =
  AppManagementRouteRoute._addFileChildren(AppManagementRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppManagementRouteRoute: AppManagementRouteRouteWithChildren,
  AppUserIndexRoute: AppUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
